name = "IPowerLab"
uuid = "a9668add-a920-4480-82b5-cfcc4aa6bd6c"
authors = ["Basel Morsy"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
